name: post-release-workflow

on:
  release:
    types: [released]

env:
  NODE_VERSION: 22
  # NODE_OPTIONS: --openssl-legacy-provider

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      node_version: ${{ env.NODE_VERSION }}
    steps:
      - run: echo "Exposing env vars"
  sites:
    needs: [vars]
    uses: ./.github/workflows/_deploy-sites.yml
    with:
      node_version: ${{ needs.vars.outputs.node_version }}
      deploy_docs: true
      deploy_redirect: false
      deploy_sandbox: false
    secrets: inherit
